### ISSUE TITLE
Outlook class KP emails as SPAM or Display alert on message header

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#100]
## Issue Description
Hello,
when i sent test emails , outlook block email links and notify user that it's dangerous e-mail, is there any  method or idea to by pass outlook fmail filter, 

![outlook filter note](https://cloud.githubusercontent.com/assets/18242158/14531991/4a80b19c-0257-11e6-8e3b-4d4c681f1c3c.PNG)

**Comment by zeroSteiner** [comment]
Yes you need to recraft your email and in the immortal words of Offensive Security, try harder.

Because the message was sent by King Phisher this isn't a problem in the application. Please do research into phishing techniques and how to bypass spam filters, these techniques are not tool specific and can easily be applied to your campaign run through King Phisher.
