### ISSUE TITLE
Time interval difference between the real time visit and the visits Timline graph

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#103]
Hello,
KP  displays visits with a difference (-1 hour) on the visits timline graph, on the dashboard, please see the attached files;
![timeline graphe](https://cloud.githubusercontent.com/assets/18242158/14672797/0d09e78a-06f2-11e6-8f3a-10fb7ba58c60.PNG)
![visits](https://cloud.githubusercontent.com/assets/18242158/14672798/0d0b7afa-06f2-11e6-911e-9ec0cd6149a5.PNG)

**Comment by zeroSteiner** [comment]
I was able to reproduce this, and the difference is due to how timezones are handled. All times are stored in UTC on the server and converted to the users local timezone in the client. In this case the Visits Timeline graphs was **not** converting the timestamps from UTC to local.

This has been fixed in commit d67e71d6, thanks for reporting it.

**Comment by Itrustsecurity** [comment]
thank you , but can u please tell me how to correct this probleme, should i modify the code source on : king_phisher/client/graphs.py
first_visits = [visit.first_visit for visit in visits]
 +		first_visits = [utilities.datetime_utc_to_local(visit.first_visit) for visit in visits]

**Comment by zeroSteiner** [comment]
No you should never ever ever modify the code because if you do you will no longer be able to update without alot of additional complexity that I can't begin to support. You have to wait for the changes to be merged into the master branch or opt in to beta testing to get them now. If you choose to opt into beta testing, there are instructions in the wiki on [how to do this](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

**Comment by Itrustsecurity** [comment]
Ok thank you;
