### ISSUE TITLE
KP Compagne preparation

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#104]
Hello @zeroSteiner ,
we are going to start a phishing compagne of more than 13000 users , what do you recommande us, 
for email list that contain more than 13000 users is it better to splie it on 3 lists or use all in one list,
i want you give us more recommandations befor starting the compagne

Thank You

**Comment by zeroSteiner** [comment]
Send all 13000 at once. In the future please try to limit opening issues to legitimate bug reports. This is third day in a row that an issue with a basic questions has been opened and I can't continue to answer each one. I suggest you try to answer your questions through experimentation and trial and error in the future instead of coming straight here to ask.
