### ISSUE TITLE
Make data anonymous

### ISSUE THREAD

**Issue by lokem87** [securestate/king-phisher#108]
Hello,

is there an way to make data anonymous? To only log for example the randomised id of the target and not the mail address, browser agent etc?

Regards

lokem

**Comment by zeroSteiner** [comment]
No there is not. That data is all stored on the server, and because of the degree to which alot of the analysis code requires it I would not be comfortable making storage of it options.

You could forge or not provide the first and last names in the targets list, and [not log passwords](https://github.com/securestate/king-phisher/wiki/Creating-Server-Content#pages-for-not-logging-passwords).

During our campaigns, we generally try to gather as much data as we can.
