### ISSUE TITLE
WebKit2GTK+ Is Unavailable

### ISSUE THREAD

**Issue by anhp11** [securestate/king-phisher#123]
## Issue Description
When trying to start Site Cloner in King Phisher, I got an error saying that WebKit2GTK+ package is not available.

## Reproduction Steps
1. Start King Phisher client on Windows
2. Click on Tools > Clone Web Page

## Environment Details
Host OS: Windows 7

## Error Details / Stack Trace
![screen shot 2016-06-15 at 9 29 20 am](https://cloud.githubusercontent.com/assets/8727495/16081504/aae69db2-32db-11e6-98b9-cc875924c797.png)

**Comment by zeroSteiner** [comment]
As it states the WebKit2GTK+ package is unavailable on Windows. This is due to limitations and bugs in the upstream repository that we're trying to resolve. At this time the we've cloning capabilities require that package and because of that are only available on Linux. If you require that feature I recommend you switch to Ubuntu 16.04 LTS for your King Phisher client.
