### ISSUE TITLE
can't access landing pages

### ISSUE THREAD

**Issue by smscjim** [securestate/king-phisher#128]
## Issue Description
I set KP up as a VM in VitualBox. I have the server and client running on the same box.  I'm wanting to use this to test employees in our company.  I was hoping to just be able to set it up locally so that it would work for employees connected to our internal network. I was able to set everything up and I can send test emails to myself but the landing pages dont work.  So I went back to the server_config.yml and changed the server address host to the IP of that machine, but when I do that, I can't log into the client.  On the client, if i change the server IP from localhost:22 to my IP address I get prompted with a message asking if I trust that server.  I click accept and then I cannot log in and am given a denied access error.  What am I missing?

## Reproduction Steps
Click on link in email

## Environment Details
Kali Linux

```

**Comment by zeroSteiner** [comment]
The server's address in the configuration needs to be left at the default value of `0.0.0.0` so that it binds to all interfaces. If you're getting access denied you need to double check that your username and password are correct. **King Phisher does not create an account for you.** The account you log in with is a standard system account on the server such as "root" in the case of Kali.

**Comment by smscjim** [comment]
ok I set the address back to the default value of 0.0.0.0 and restarted the server.  i was able to log into the client.  In the configuration home page I was able to "verify URL."   I sent another test email to myself and I am getting the 404 not found error.   I've read through the FAQ about this error but I cant seem to figure out exactly what I am doing wrong.

**Comment by zeroSteiner** [comment]
1. Does the URL in your test email (and by extension the link you click) include the `?id=` parameter?
1. What does King Phisher say when you select "Verify URL"?
1. What lines are in the server log when you attempt to click the link?

**Comment by smscjim** [comment]
1.  Yes it includes the ID parameter.
2.  it says "Successfully opened the web server url"
3.  server logs say "INFO    localhost "RPC /db/table/count HTTP/1.1"  200  -
                               "INFO running RPC method:  /db/table/count"

Its almost like the server is even seeing the requests.  When i click on the links the information in the logs doesn't change.  I ran a debug and again it doesnt change either.

**Comment by smscjim** [comment]
*server isn't even seeing

**Comment by zeroSteiner** [comment]
I would agree, it does not look like the server is receiving the requests. There should be at least 1 line per request with logging set to DEBUG. It sounds like a networking error. When you try to visit the link, what exactly do you see in your browser?

**Comment by smscjim** [comment]
![image](https://cloud.githubusercontent.com/assets/19981512/16347661/f2994f6e-3a1b-11e6-9306-6ebcb32a1911.png)

**Comment by smscjim** [comment]
maybe there is a setting in virtual box that needs to be changed?

**Comment by zeroSteiner** [comment]
I don't know what page that is but it is *not* the King Phisher 404 page. Your link is not making it to the server, it sounds like a networking issue that you need to fix on your end. There could very easily be a setting in Virtual Box that needs to be changed if you're using NAT or something similar.

Because this problem is not an error with King Phisher, I'm going to close this out. Unfortunately we can't help you troubleshoot networking problem.
