### ISSUE TITLE
Tracking opening of attachments

### ISSUE THREAD

**Issue by n-kostya** [securestate/king-phisher#135]
Is there a way to add the tracking functionality to the attachment sent by King-phisher?

We want to keep track of how many people actually open the attachment but i can't seem to find any details. Is it possible to use the Jinja tags in a similar manner as we do with the emails?

**Comment by zeroSteiner** [comment]
Unfortunately it's not possible to track attachments that have been opened. We've looked into this in the past pretty extensively.

The problem exists in the ambiguity of an attachment. King Phisher would need to understand the format (ie XLSX, zip, EXE, etc.) in order to be able to patch in the unique message ID. Furthermore, the file would need some kind of mechanism to use that ID in a request to the server for it to be registered.

Office documents that use macros are a good example of this. There is not a suitable Python library to insert a malicious macro into an existing document.

**Comment by W1R3D-Code** [comment]
Something you may already have considered, but given that the newer Office Docs are just zipped XML, if you read in as a zip and add/edit '/docProps/custom.xml' you can set the value of a custom prop

i.e.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="King-Phisher"><vt:lpwstr>123456</vt:lpwstr></property></Properties>
`

then you can reference it by name in macros and pull the value out 

`ActiveDocument.CustomDocumentProperties("King-Phisher").Value`

**Comment by zeroSteiner** [comment]
@W1R3D-Code I had not considered that, but it's a great idea.

A similar technique is also available using the [phisher](https://github.com/securestate/king-phisher-plugins/blob/master/client/phishery_docx.py) plugin which patches in the messages specific tracking ID.
