### ISSUE TITLE
"Visitor Agent" and "Opener user Agent"

### ISSUE THREAD

**Issue by smscjim** [securestate/king-phisher#144]
I started a campaign yesterday and I'm a little confused on the results.  Specifically for the Visitor User Agent in the Visits tab and Opener User Agent in the Messages tab.   Are these two not the same?    On the Dashboard I can see this:
![image](https://cloud.githubusercontent.com/assets/19981512/17628200/48c3d2f6-6082-11e6-97b6-904097ea92f5.png)

But in the Messages tab under the Opener User Agent there are way more than 49 visits,  its more like 71.  In the Visits tab there are exactly 49 visits.  

Shouldn't these be the same or is the Opener User Agent different from Visitor User Agent?

**Comment by zeroSteiner** [comment]
No they are very different, the opener user agent is the user agent of what is most likely the email client (i.e. GMail, Outlook etc.) that requested the tracking image from the server.

Just because the email was opened does not mean that the user visited the landing page which is what is required to register a visit and why you see more "Opened User Agent" entries than visit entires. Emails being opened should be considered completely different than visits because visits may come from someone who didn't load images (and thus did not register an opener user agent) or may not come from someone that did load images.

**Comment by smscjim** [comment]
Ok that makes sense.  So is it safe to assume that the Opener User Agent is for people who I guess "opened" the email, and didn't just view it in a preview plane on their email client?

**Comment by zeroSteiner** [comment]
It's for people who's email clients loaded the images embedded in the message. Each email client is different in it's behavior so whether they simply previewed it or opened it, I can't say for certain without looking at the client.

**Comment by smscjim** [comment]
Ok, this is at work, and everyone has the same email client,  different software versions tho and some do read email from a web browser.  So maybe I wont include these numbers in any sort of report.  But for sure in the Visits tab, the Visitor User Agent shows how many people clicked on the link in the email and at a minimum visited the site?

**Comment by zeroSteiner** [comment]
Each row in the Visits tab represents a user who clicked on the link and loaded the landing page.

**Comment by smscjim** [comment]
Excellent!  thanks!!!
