### ISSUE TITLE
Error occured while sending mass mailing

### ISSUE THREAD

**Issue by twkrol** [securestate/king-phisher#172]
## Issue Description
I get a stack trace when I'm sending mailing

## Reproduction Steps
1. Start King Phisher
2. Select campaign
3. Set mailing params, target csv file and Send
4. After some random amount of e-mails an Error occurs

## Environment Details
Host OS: Ubuntu 16.04 LTS
Client Host: Windows 10 Pro 64bit

## Error Details / Stack Trace
Error Type: advancedhttpserver.RPCError
Error Details: RPCError(message='Unauthorized', status=401, remote_exception=False)
Error UID: ffbfbef3-d248-44cc-81c5-2006d54d2e54
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.5.1
Platform Version: Windows: 10 10.0.14393  Multiprocessor Free (Frozen=True)
Python Version: 2.7.12
Gtk Version: 3.14.15
Timezone: Europe/Warsaw

Thread Information:
    Thread-2 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)
 => MainThread (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\tabs\mail.py", line 268, in signal_button_clicked_sender_start
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\tabs\mail.py", line 151, in _sender_precheck_campaign
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\client_rpc.py", line 246, in remote_table_row
  File "C:\Python27\lib\site-packages\advancedhttpserver.py", line 565, in call
RPCError: the server responded with 401 'Unauthorized'

**Comment by zeroSteiner** [comment]
We unfortunately see these errors periodically and they're notoriously difficult to reproduce. If we're going to have a shot we'll need to know more details around the timing that you're using. What is the delay in between emails and how many are you trying to send?

The 401 RPCError is typically associated with the token timing out, which obviously shouldn't be happening under normal conditions. What would also be helpful for troubleshooting this would be the server logs corresponding to the same error.

**Comment by zeroSteiner** [comment]
This issue has now been fixed in the dev branch. To obtain the changes, you can either wait for them to be merged into the master branch (which will likely take a few weeks) or you can obtain them immediately by opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

Attempted to resolve this with commit 118e8044 which adds automatic "pinging" of the server over the RPC interface every 5 mintues. This will keep the RPC session alive. It would be an extreme condition in which the RPC session would expire with the default time out of 30 minutes as the graph idle_handler would have to not run 2x be disabled etc.

Anyways this should help eliminate the possibility of the session expiring prematurely while the client is still alive.
