### ISSUE TITLE
Poor support (or documentation) of Kali Linux Distro

### ISSUE THREAD

**Issue by mozg31337** [securestate/king-phisher#25]
Since a lot of professionals are using Kali to perform their security auditing it would be very nice to have a fully documented way of having all the niceties of KingPhisher working under Kali Linux. Even better, a working support of Kali under the install.sh script.

At the moment, it is tricky to get things working with various dependencies. For instance, integration of matplotlib is totally broken regardless if you are installing it from the apt repo or by using pip / easy_install.

**Comment by zeroSteiner** [comment]
I can certainly look into the matplotlib issue. For the other missing niceties, it would be helpful if you could provide a detailed list of which features are missing / broken.

The only other feature I can think of right now is web cloning which is a compatibility issue due to Kali providing an old version of GTK (3.4 last I checked). Additionally if you're interested in better support for King Phisher on Kali, there is an [open support ticket](https://bugs.kali.org/view.php?id=2137) requesting that it be packaged and added to the official repos that has not gotten much movement presumably due to a lack of community interest.

**Comment by mozg31337** [comment]
I am still having issues with matplotlib in Kali, which is why I am using the kingphisher client app from my Ubuntu laptop, which is not ideal for me. On ubuntu 15.04 things have installed pretty nicely tough.

However, I remember I was having a few issues with dependencies when I was first installing KingPhisher on the Kali Linux. You have helped me with sorting those out, which was a big help.

Perhaps having a proper package / ppa style distribution of KingPhisher would be ideal ))

**Comment by zeroSteiner** [comment]
A proper package would definitely be a nice thing to have. However given my limited resources it's not a task that I am personally interested in pursuing in the foreseeable future.

Moving forward, I need details on what issues you're having with matplotlib on Kali. The provided install script *should* install all the required native packages necessary to build it from pip, and before each major release I test the install script on a fully updated and fresh image of Kali. I'll need a stack trace of matplotlib running or some kind of details in order to proceed and address the issue.

**Comment by zeroSteiner** [comment]
So I still need some details on what exactly is failing with matplotlib on Kali. A stack trace, installation error message or description of what features are not available would be great.

**Comment by mozg31337** [comment]
Hi Spencer, 

It is on my todo list and I will try to do it over the weekend or next week as I am pretty busy with a project at the moment. 

Thanks for your patience, 

Andrei 

----- Original Message -----

**Comment by zeroSteiner** [comment]
I'm going to go ahead and close out this issue. If you get some time and want to take it up again I'd be happy reopen it. Requests for documentation are important, I just need more details as to what the current limitations are.
