### ISSUE TITLE
Email sending error

### ISSUE THREAD

**Issue by SJHsimkaur** [securestate/king-phisher#255]
## Issue Description
When i trying to send an email but i am getting this error

## Reproduction Steps
1. Start King Phisher
2. Launch new campaign 

## Environment Details

Host OS: Ubuntu 16.04 GNOME DESKTOP, 
King Phisher Version: 1.9.0

## Error Details / Stack Trace
checking target URL.... success,done
Skipped checking SPF policy because SMTP server address could not be detected.
Sending messages started at Thursday Jan04....
Message mode is: Email

```

If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
I don't see any error details here. Are you referring to the message regarding checking the SPF policy?

**Comment by SJHsimkaur** [comment]
Actually, I am not receiving any email.

**Comment by SJHsimkaur** [comment]
I am little confused here to get this email working. Please correct me if I am wrong - 
Can i use our organisation SMTP server or need a local SMTP on KP server. Also I am able to receive email sent directly from the server. 

here are few logs from /var/log/mail.log 
Jan  5 09:28:22 king-phiser postfix/pickup[15770]: BA3028ACDC8: uid=0 from=<root@king-phiser.stjosham.on.ca>
Jan  5 09:28:22 king-phiser postfix/cleanup[16370]: BA3028ACDC8: message-id=<20180105142822.BA3028ACDC8@king-phiser.stjosham.on.ca>
Jan  5 09:28:22 king-phiser postfix/qmgr[1719]: BA3028ACDC8: from=<root@king-phiser.stjosham.on.ca>, size=383, nrcpt=1 (queue active)
Jan  5 09:28:22 king-phiser postfix/smtp[16372]: BA3028ACDC8: to=<myid>, relay=<org relay server> delay=0.24, delays=0.02/0.01/0.03/0.18, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 243ECEF4C66)
Jan  5 09:28:22 king-phiser postfix/qmgr[1719]: BA3028ACDC8: removed

This shows message is sent but never received. Please advice.

**Comment by zeroSteiner** [comment]
You can use any SMTP server that you'd like, there are even instructions for [Public SMTP Servers](https://github.com/securestate/king-phisher/wiki/Public-SMTP-Servers). Additionally, servers that require authentication are supported as well.

The actual delivery of the message once King Phisher has handed it off to the SMTP server is out of the scope of our project due to being out of our control. Because of this, we can not provide support for debugging and trouble shooting your SMTP server's configuration and performance.

I would recommend starting by trouble shooting your SMTP server's configuration and ensuring that it is functioning with another application other than King Phisher. Good luck!
