### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by rageissweet** [securestate/king-phisher#267]
Hi, sry for my english  ;)
if i run a campain in King phisher, it sends the messange and the victom can open it ;)
but there  is no result in the dashboard . 
in terminal is follwing output 
------------------------------------------------------------------------------------------------------------------------------
ERROR    error uid: 008b5881-9e17-4df3-9d1e-e15ccebe571a an unhandled exception was thrown
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/windows/main.py", line 312, in signal_login_dialog_response
    _, reason = self.application.server_connect(username, password, otp)
  File "/usr/share/king-phisher/king_phisher/client/application.py", line 606, in server_connect
    login_result, login_reason = rpc.login(username, password, otp)
  File "/usr/share/king-phisher/king_phisher/client/client_rpc.py", line 347, in login
    login_result, login_reason, login_session = self.call('login', username, password, otp)
  File "/usr/lib/python3/dist-packages/advancedhttpserver.py", line 573, in call
    raise RPCError('remote method incurred an exception', resp.status, remote_exception=resp_data['exception'])
advancedhttpserver.RPCError: a remote exception occurred

(KingPhisher:4027): Gtk-CRITICAL **: gtk_assistant_set_page_has_padding: assertion 'child != NULL' failed

(KingPhisher:4027): Gtk-CRITICAL **: gtk_assistant_set_page_has_padding: assertion 'child != NULL' failed
WARNING  received a socket.error while connecting to the SMTP server
--------------------------------------------------------------------------------------------------------------------------------

what can i do ?
greets

**Comment by zeroSteiner** [comment]
Next time, please fill out the issue template in it's entirety instead of ignoring it. We often need to know details such as what version you're running and what the host OS is. Please include this information in your response.

It sounds like visits are not getting logged but that doesn't make sense with the stack trace you've provided. I'm guessing the issues are not related.  To ensure that visits get logged, you need to make sure that the message ID is included in the link the target clicks on. This should look like `?id=SOMESTRING` at the end of the URL. This automatically handled if you use the Jinja variable `{{ url.webserver }}` in your email template.

What does the client see if they visit the page? Do they get a 404 response or do they see the web page? Also, the web page you're directing them to is on the King Phisher server right? If it is you should get messages in your server log file that may come in handy for debugging this issue, especially if the target is receiving a 404 response.

**Comment by rageissweet** [comment]
Hello, thanks for the answer.
sorry that I have ignored the output template.
my system is kali 2018 and I cloned the KP version today from the git page.
the website does not see the target 404, everything can be clicked on.
the url ends with
? Id = gtxV0YpL9GfoQJZq & utm_expid = .zs9JVjHyR-mPYGSqNRkHgg.0 & utm_referrer =
Is that correct?
now new problems appear, after 2 error messages,
Error Type: builtins.AttributeError
Error Details: AttributeError ("'AxesSubplot' object has no attribute 'set_axis_bgcolor'",)
Error UID: 0e3646c5-ddd5-415c-acbf-65698e661352
RPC Error: N / A (Not a remote RPC error)
King Phisher Version: 1.10.0-beta (rev: 6bab024ed811)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.4
Gtk version: 3.22.28
Timezone: Europe / Berlin


 
--------------------------------------------------
Error Type: advancedhttpserver.RPCError
Error Details: RPCError (message = 'Unauthorized', status = 401, remote_exception = False)
Error UID: 6cfc54d5-f16d-40d6-9a71-4035da28ed88
RPC Error: N / A (Not a remote RPC error)
King Phisher Version: 1.10.0-beta (rev: 6bab024ed811)
Platform Version: Linux: Kali
-------------------------------------------------- -------
which always come, I can indeed send messages, but can not call the dashboard and therefore no longer check whether antworet comes :(
does it bring anything if i reset the complete installation?
if so, how do i get all the data deleted, the data like smtp server seems to be still present after a new installation.
sorry for the many stupid questions, I'm stuck, greetings

**Comment by zeroSteiner** [comment]
I don't understand "the website does not see the target 404". When the link in the email is clicked does it take you to the King Phisher server and do you receive a 404 error or are you seeing the correct landing page? It might be helpful to include the last 20 lines of the server log file when the link is clicked.

**Comment by zeroSteiner** [comment]
The `set_axis_bgcolor` issue was fixed in commit 531eb81697aec23363c7536ab32ec3b964c6e5ed, see #269. You can update and then run `sudo python3 -m pip install -r requirements.txt` to install the correct version of matplotlib.
