### ISSUE TITLE
Unique id's question

### ISSUE THREAD

**Issue by Valraven** [securestate/king-phisher#271]
Not really an issue, but more of a question. The unique id's that are generated, is it possible to get them only in lower case? Because I have noticed that there are sandboxing programs out there that sandbox emails that have been received and then generate a secure link for the receiving party, but when visiting that link all the uppercase characters have been put to lowercase.

So is there a setting where the unique id's only get generated with lowercase, or in a way that it doesn't matter what kind of case comes in as a request?

**Comment by zeroSteiner** [comment]
No to both. We definitely can't make them case in-sensitive because that would affect how existing data was treated and associated with the various campaigns.

We might be able to put an option together to simply generate UIDs that are all lowercase though because they're generated client-side.

**Comment by Valraven** [comment]
That option would be awesome to have :)

**Comment by Silburfuchs** [comment]
@Valraven have you seen this across multiple sandboxing services or are have you noticed this in one in particular?

**Comment by zeroSteiner** [comment]
While we consider this internally you can acheive the desired effect by changing [king_phisher/utilities.py:385](https://github.com/securestate/king-phisher/blob/91fb64a3b581ce1e95df04b44fa3480ec61f38dd/king_phisher/utilities.py#L385) to:
`return ''.join(random.choice(string.ascii_lowercase + string.digits) for x in range(16))`.

**Comment by Valraven** [comment]
Hey thanks for the replies and the help to fix the problem right away. Currently we have only seen it on one sandboxing service. And even our customer that asked for the phishing campaign (as we do user awareness testing as a company) is kinda like: This is unacceptable that the sandboxing service does this, as it also blocks out for example youtube links or other case sensitive legitimate sites.

But I figured I would put this problem out there and help you guys make King Phisher more awesome for future problems on this lowercase-uppercase problem :)

**Comment by zeroSteiner** [comment]
Quick update, we discussed this internally and figured out how we'd want to implement this. We just released version 1.10 today so we're going to target the next release in 1.11. What this means is it'll unfortunately be a while until the feature is first implemented then merged into master.

**Comment by zeroSteiner** [comment]
Behold, it is done!
![screenshot from 2018-04-06 11-57-23](https://user-images.githubusercontent.com/2058303/38431299-c901a6de-3991-11e8-95c5-148279b26f91.png)

Couple of things to note about these changes (for future reference):
* Added a new "deferred" message sent RPC call to keep the sent property set to NULL until the message is sent when a second RPC call will be made to update it. This ensures that an exception will be raised before the message is sent in the very mathematically unlikely scenario that the selected UID collides with an existing one in the database. That'd be bad but since a configuration using strictly numbers increases this change significantly, the issue needed to be addressed.
* The new charset options are in the message configuration. This allows them to be included when import/exporting the configuration for KPM archives as well as compatibility with the [config-manager](https://github.com/securestate/king-phisher-plugins/blob/master/client/campaign_message_configuration.py) plugin.

Changes are in the `dev` branch now, you can opt into [Beta Testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing) or wait for the next  stable release to obtain these changes.
