### ISSUE TITLE
Collecting Browser Plugin Information

### ISSUE THREAD

**Issue by justaskingquestions** [securestate/king-phisher#296]
How can I collect and report informaiton about the browser plugins (Adobe Flash, Shockwave, Java etc.) of users visiting the links in my phishing campaign?

**Comment by zeroSteiner** [comment]
We don't support collecting this kind of information at this time.

**Comment by justaskingquestions** [comment]
Man you are fast! Thanks for clarification.

**Comment by zeroSteiner** [comment]
Yeah, that's something that's on our radar but I don't want to say we'll get to it and then not because it's a bit of a lower priority. One thing we are more likely to move towards with a higher priority is distribution of templates through a similar system as the plugin store, and much better support for providing training to users through multi-question tests instead of a simply "Yes this user was trained or No this user was not".

I'd like to get to this at some point, but unfortunately that day is likely over a year away.
