### ISSUE TITLE
Issue with Visits

### ISSUE THREAD

**Issue by riveta** [securestate/king-phisher#31]
Message and Visits feed not displayed. Kindly help with requisite configuration

**Comment by zeroSteiner** [comment]
The messages tab is populated as emails are sent. Are you having trouble sending emails?

**Comment by riveta** [comment]
I am able to send emails and I get the list of email address and sent time in the message tab but I don't see any data if the recipient has opened the mail under message tab and no data in the visit tab.

**Comment by zeroSteiner** [comment]
So the opened column is set with a timestamp under 2 conditions. 1) If the tracking image was included in the email and the recipient's email client loaded it or 2) a first visit was received by the recipient clicking the link.

It sounds like no one has opened your messages because they would show up under the visits tab. The tracking image is not always reliable depending on the email client the recipients are using.

**Comment by riveta** [comment]
Thank you. I'm certain that people have opened my emails and visited the target page too. But the issue remains. Could you please help me out with where exactly the landing pages are to be appended.

**Comment by zeroSteiner** [comment]
The landing page is set from the URL configured in the message settings tab when the messages are sent. Are you including the UID in the URL that is being sent?

**Comment by riveta** [comment]
Hi thanks for the help. I had the landing pages loaded wrong. I figured it out now.
