### ISSUE TITLE
King Phisher Campaign results

### ISSUE THREAD

**Issue by will287** [securestate/king-phisher#323]
## Issue Description
I experience an issue when I... and the results I expected are...
Does King Phisher have a log file that captures the results of a campaign on the king phisher server. I was able to run a campaign. I got an error during the sending of email. They all appeared to send ok. We had quite a few user input credentials. However I can not see the results in the client GUI ? 
1.) Are the results stored on the server in a log or other location?  

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Kali Linux 2018 
King Phisher Version: 1.11.0 python version 3.6.6

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by wolfthefallen** [comment]
The server part of King Phisher by default logs to `/var/log/king-phisher.log` ..
All the information for the campaigns are stored in the database the King Phisher Server is pointed to. Generally it is a postgresql database, if you select yes to that option during installation.

If no creds are showing up in the GUI, there is a high probability the page you where using to collect creds was not correctly setup. Did you test it prior to sending out the phish to make sure you where getting results?

**Comment by zeroSteiner** [comment]
It's also possible that your campaign ID changed if your client configuration was corrupted. Go to `File > Open Campaign` and make sure you have the right one selected.

**Comment by will287** [comment]
Yes it was tested and everything was working correctly.  Is it possible to find some of the results on the server? 
Would the server at least capture the site visit information? We don't need the credential information.

**Comment by zeroSteiner** [comment]
Yeah your best bet would be checking the database. If the client isn't showing the data though, it might not be in the database.

If your database is postgresql, check out the pgsl command and look in the campaigns, messages, and visits tables filtering by your desired campaign ID. 

If that's the case you'll have to check the logs and hope the verbosity was set to a level that captured what you need.

**Comment by will287** [comment]
I understand the above comments and thank you. Maybe is should start a new issue. 
I rebooted the server I changed in the server_config require_id to false. I sent a new single email to from the client  1.11.0 I can see all of the other sent email in the list the single email I sent is at the bottom of the list. The email was received the test user open the email clicked the link and was directed to the landing page :) . The user inputted their credentials user name and password. They do not appear in the king phisher client. 
I have DEBUG enabled on the server and i can see the user name and password that were entered into the landing page. However they are not visible in the client v1.11.0

**Comment by zeroSteiner** [comment]
Can you share the DEBUG line you're referring to? Of course change the username and password. Can you also include a few lines before and after it?

**Comment by will287** [comment]
![image](https://user-images.githubusercontent.com/32827200/46211322-41230d80-c301-11e8-8712-ec60be566f2d.png)

**Comment by will287** [comment]
So to recap this single email campaign went out the user input the user name and password. I can seen in the client that the email was sent with the correct date and time stamp. However I can not see the visit hit or the credentials that were imputed.

**Comment by zeroSteiner** [comment]
This is really helpful, thanks. **TLDR:** You can't use tinyurl.com as your landing page if you don't own that domain and have it pointing to your King Phisher server.

So it looks like you're landing page is hosted on hxxp(s)://tinyurl.com right? So because you're using a URL shortener, King Phisher is logging that as the "landing page". The landing page is a special variable that King Phisher tracks for you automatically and associates one or more with your campaign. Now when a visit comes into the server with a message ID it will be logged as a visit and a "session" will be created (just like in a normal site with a cookie). Once the session is established the visitor can go to other pages, including non-landing pages, and for example enter their credentials. However if the landing page is not hosted on the King Phisher server a visit will never be logged and a session to log credentials will never be created.

You can more easily debug and check this by setting `require_id` to true in the server. When that's enabled the only way to get to a non-404 page is to have a valid message ID associated with a non-expired campaign and be requesting a landing page associated with that campaign. After that you'll have a session and can visit other pages.

**Comment by zeroSteiner** [comment]
So that graph shows you do have credentials though. Is the issue just that they're then not showing up in the credentials tab? Or are there specific instances of credential submissions that aren't showing up while other ones are?

**Comment by will287** [comment]
The above is a sample campaign with the same url. It shows credentials under the credentials tab. However the large campaign we conducted only shows who the messages were sent to it does not show any information such as visits or credentials. As you can see from the DEBUG log above I am capturing credentials in the system.

**Comment by zeroSteiner** [comment]
And the URL for both is the tiny URL? Because it doesn't seem like that should work for either because of the landing page issue I outlined above.

**Comment by will287** [comment]
yes it is the same tiny URL.... It actually has worked for several campaigns in the past. This is all taking place on an internal network

**Comment by zeroSteiner** [comment]
Did you upgrade your server right before running this campaign and if so do you remember the version before and after?

**Comment by zeroSteiner** [comment]
Alright I just tested this and as I suspected it does not work. The only way I can think that it ever worked and recorded data would be if you followed the following specific steps:

1) Disabled `require_id` in the server config
2) Created "Campaign A" and set the target URL to a hostname pointing to the King Phisher server
3) Sent a test email and saw everything worked correctly
4) Created a Tiny URL to the replace the original URL created in step \#2 
5) Ran the campaign and had profit
6) Created Campaign B and left the Tiny URL in the place
7) Ran the campaign and no data was collected despite the URL appearing to function (due to the `require_id` setting)

These specific steps are all I can think of that would reproduce the issue you're describing unless there are additional details you haven't mentioned. The reason why it would appear to work is that in step \#3 King Phisher automatically created a landing page that was later used for the Tiny URL and associated it with Campaign A. However when you moved on to Campaign B, since the URL didn't need to be changed I'm guessing your skipped setting it back to a URL with a hostname pointing to the King Phisher server because you would not have had any reason to test it again. Now you sent messages in step \#7 visitors saw the page because you disabled (require_id) but nothing was tracked since they weren't landing on the landing page due to it being a Tiny URL and the hostname of `tinyurl.com` did not match the incoming requests.

Or right before this campaign you updated from a really really old version of King Phisher, like 2+ years old, where it was more liberal in tracking visits by having no concept of a landing page.

That's it, that's the best explanation I've got.

**Comment by will287** [comment]
I did not upgrade the server and everything works as expected. 
However I have created a new campaign about 20 min ago and the results are as you described with the tiny URL. If I use the physical IP or FQDN address of the server it collects information. 

I think I may have been lucky on the first couple of events.

**Comment by zeroSteiner** [comment]
There had to have been multi landing pages associated with those campaigns where at least one was the target of the tiny URL. Unfortunately I think that data you had is lost unless you can extract it from the logs.

**Comment by zeroSteiner** [comment]
We should could do a better job of documenting this in the future. Ideally there would be a way for us to automatically identify this scenario and account for it by updating the landing page but that's easier said than done due to the server not knowing all of its IP addresses and hostnames.

**Comment by will287** [comment]
For the record tiny URL's work in some cases.  The use of tiny URL is not reliable. Looks like we will have to conduct another campaigns sooner then scheduled. 
Thank you for you assistance

**Comment by zeroSteiner** [comment]
Yeah like I outlined [above](https://github.com/securestate/king-phisher/issues/323#issuecomment-425554011), TinyURL would work under those key circumstances. This is a byproduct of how King Phisher functions and you'd need to reproduce steps 1-5 every time to use TinyURL.

In the future though, you shouldn't use any URL where the hostname does not point directly to the King Phisher server as this is not intended to work and as you've seen your mileage may vary.
