### ISSUE TITLE
Login Authentication Documentation

### ISSUE THREAD

**Issue by zeroSteiner** [securestate/king-phisher#335]
I have been searching all over for better documentation on this app also. I keep reading where the contributors say there is tons of documentation etc. blah blah blah. Yeah, this is true, there is TONS of documentation on installing and starting up this app, however there is practically NO DOCUMENTATION on the login and password setup of King Phisher and how it reacts on different distros. For example I have read that on Kali, it uses the users login and password...yet this is not true on Parrot Security. Neither is it true if you do a clone or manual install, I have watched the install as it clearly states it CREATES A RANDOM PASSWORD in the sql db. Doesn't bother to tell you what that password is. I assume that is the password needed since it must connect to the db to work. This is an excellent app from what I can see, so why can't someone take a little time to make it MORE CLEAR how to setup and use the login and password? to Login Authentication Documentation 

At this point I am now about to go digging around my postgresql db to see if I can find an entry from king phisher and figure out how to make it go from a worthless install to something useful...

Am I frustrated? Yes, very! I have it installed perfectly, all dependencies, everything ready to go and no login or password to actually use it. Wouldn't you be frustrated too? That's like buying a new sports car without the dang keys to actually start the thing!!!

_Originally posted by @PaganGuy in https://github.com/securestate/king-phisher/issues/330#issuecomment-439906862_

**Comment by zeroSteiner** [comment]
Reading through that wiki page now, it doesn't really talk about PAM at all or why we use it. It's mostly for configuring the client to authenticate to the server but before I go in and start making a bunch of changes to the content I'd like to get your opinion on what you think would help clarify things.

**Comment by PaganGuy** [comment]
zeroSteiner - First off THANK YOU! So, after reading your reply it was like a light bulb went off and within 2 minutes I had King Phisher up and running. Then it dawned on me what the issue is, but I must admit I am not quite sure how to fix it so I will leave that up to you. Honestly, it is how it is worded... It has to be, because as soon as I read your response it all became clear to me. It also needs to be very clear it is connecting using SSH I suppose in response to a lot of the other questions I have seen, folks seem to miss that. What I missed was that it sets up its own postgresql business we just need to setup, run, and use our SSH to connect and it does the rest...if that makes sense. Like I said, I will leave it up to you to figure out how to fix the confusion, but I am sure it is just simply how it is worded. 

Works beautifully btw, awesome job on this application. I am a Software Systems Engineer myself so it is definitely not lost on me how much hard work went into this application so thank you very much for your hard work. Also, thanks for such a speedy reply, I honestly did not expect a response for a few days. =)

**Comment by zeroSteiner** [comment]
"...it sets up its own postgresql business we just need to setup, run, and use our SSH to connect and it does the rest...if that makes sense. " That does and that's entirely correct but I can see how it may not be super clear in some sections. I've got some ideas on how I can try and expand out the wiki pages on this topic. I'll leave this issue open until I've gotten around to making the relevant changes which will hopefully be within the next few days.

I'm glad you got it up and running now!

**Comment by PaganGuy** [comment]
also, I have my won web site and a section on pentesting where I have made it my mission to start making very clear, English speaking, non-blurry as hell tutorials using Parrot Security OS for cyber security and pentesting work. I will definitely be including a tutorial on installation and setup of your awesome app when I get my subscribers to that point of their learning. Hopefully I will be able to help clear the confusion with you about this awesome application. 
I am doing this because a lot of the tutorials I have seen are very blurry, mostly non-English speaking narrators, and rushed. Not knocking anyone that does not speak English, there is just a great lack of these English speaking tutorials in general. Also, they all rush through the tuts assuming a lot as they go. I don't want to give folks things to memorize for that one single thing, I want to teach them useful things they can learn, remember, and apply elsewhere in their learning travels. My tutorials are rather long, but I go over everything so nothing is lost or assumed for the end user.
If you are in agreement, I would really like to send you a link to the non-published tutorial when I complete it to get your input before I publish it. I would love nothing more than to help clear up some of the confusion, and some folks learn best by watching so I hope to reach that crowd. I have already outlined the tutorial and can see it will have to be in two parts, but that's ok, better to be clear and informative in my opinion so I am ok with that. Have an awesome day!

**Comment by zeroSteiner** [comment]
Absolutely, feel free to send it to me and I'll take a look. Then once it's done we can share it around. We're always looking for more tutorials. Another good one we've seen is more focused on Kali at [https://www.sw1tch.net/2018/07/09/king-phisher-setup/](https://www.sw1tch.net/2018/07/09/king-phisher-setup/).

**Comment by zeroSteiner** [comment]
I updated the server authentication page to mention database authentication a little at the bottom and updated the database page to mention that the install script will create the user and password by default. If anything's unclear or you have questions or comments on how we can improve the documentation just let us know.
