### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by binarymist** [securestate/king-phisher#356]
# Feature Description
Curious as to what "Docker server support has been removed" means, and why it would have been removed? Is there no Docker image or Dockerfile anywhere?

Thanks.

**Comment by wolfthefallen** [comment]
@binarymist King Phisher will still work inside of a docker image, but at this time we are no longer supporting and maintaining docker images for King Phisher. This decision was came to due to very limited use of the images from the public; to the point we went several version releases with no docker images downloaded. We have found our time to be better focused on developing new features for King Phisher.

**Comment by binarymist** [comment]
That makes sense, did you have a Dockerfile? If so could you point me to it in version control so I may use it as a starting point?

Thanks.

**Comment by wolfthefallen** [comment]
No problem

You can get access to the the docker compose and Dockerfile from commit ed2e48ef5741d714373a1e251a54d3feba5f11f9 . Then navigating to the the `data/server/docker` directory.

```
git checkout ed2e48ef5741d714373a1e251a54d3feba5f11f9
cd ./data/server/docker
```

**Comment by binarymist** [comment]
Ok, thanks for that!
