### ISSUE TITLE
General Question: Notifications

### ISSUE THREAD

**Issue by JoneSodaaa** [securestate/king-phisher#392]
Hello,

I am hosting my landing page, and it is able to be visited by following the link in the email URL. However, ever since I added the external server as the web page host instead of the local host, I am not getting notified of "visits". I am just wondering why this is and what I need to change in my configuration.

**Comment by zeroSteiner** [comment]
When you say notified of visits do you mean by SMS, email or whatever? Or that you're no longer seeing the visits register in the GUI table?

**Comment by JoneSodaaa** [comment]
All 3. However the most important thing is that they register in the GUI. Does king-phisher.com have to be hosting the landing page to get notified?

**Comment by zeroSteiner** [comment]
Well you don't own king-phisher.com, I do. So you can't host your content on that. If you're not using a landing page and a URL that's pointing to your own King Phisher server instance, then you won't get any visits registered because no one is going to your server.

You need to have your own domain, point it to your King Phisher server, host your content there and then use that as a link to send out in messages.

**Comment by JoneSodaaa** [comment]
That makes sense. But how do I make my king-phisher server live on a public IP? Everything done on the king-phisher server sits on my private IP that can't be visited external to my network

**Comment by JoneSodaaa** [comment]
That makes sense. But how do I make my king-phisher server live on a public IP? Everything done on the king-phisher server sits on my private IP that can't be visited external to my network

**Comment by zeroSteiner** [comment]
You need to own a public IP address or rent a server that comes with one (like Digital Ocean or AWS). Then once you have a server with a public IP address, install the King Phisher server on it.
