### ISSUE TITLE
Server SSh username & password

### ISSUE THREAD

**Issue by mdabzaar1** [securestate/king-phisher#410]
## Issue Description
I experience an issue when I... and the results I expected are...

## Reproduction Steps
1. Start King Phisher

## Environment Details
Kali LINUX

## Error Details / Stack Trace
USERNAME ssh and password ?

**Comment by True-Demon** [comment]
Thanks for the very intelligent and elloquent issue. Despite your incredible detail, I am having a hard time understanding your question. I'm forced to assume you don't know how to log into King Phisher or what SSH is. 

Your SSH credentials are the same as whatever user you set up on the system. If you are using Kali linux, then the username is `root` and whatever password you chose. King Phisher uses local user credentials.

In the future, please fill out the full issue template and try to use complete sentences so that people can better assist you.

**Comment by mdabzaar1** [comment]
Right, that's my doubt! I have tried it, it says server error!

**Comment by mdabzaar1** [comment]
Root n password: my Linux machine password

**Comment by zeroSteiner** [comment]
Can you SSH into the system at all? Also do you have keyed authentication required?

**Comment by joco1999** [comment]
It is also not clear to me

**Comment by hwac121** [comment]
bottom line is this, you use the SSH server login/password so the answer to this really depends on your setup. Whether you have a pre-setup system like Kali, Parrot Security OS, etc. or if you setup your system (including your SSH server) yourself. You will need to know the SSH information to use this application.

**Comment by Jackthecoder12** [comment]
How can I log in to my phisher please

**Comment by sweetjeez** [comment]
Let me know when you find out
