### ISSUE TITLE
./KingPhisher

### ISSUE THREAD

**Issue by Azuredragon-eazy** [securestate/king-phisher#413]
Loading .env environment variables…
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/king-phisher/king_phisher/client/__init__.py", line 35, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by zeroSteiner** [comment]
Please completely fill out the issue template. We need all of the details that it requests to better identify the issue and provide the help that you are requesting. Please do not open a new issue but instead just edit this one and fill out all of the details.

**Comment by Nib0x62s** [comment]
I can probably enumerate what the issue is here. Due to some permission errors you have on your system PIPENV is not picking up the correct packages and environment settings causing it to not recognize and install the required site packages. 

You can attempt to remmediate the above explained issue by running: `export PIPENV_VENV_IN_PROJECT=True && sudo -E pipenv --site-packages install` in the install directory of kingphisher, however, i'd recommended you re mediate the systemic issue with permission on your system as well to prevent further issues if this does re mediate the problems you're experiencing. 

This is all just an assumption however. If you could fill out the form completely as requested previously we'll be able to provide better assistance :)
