### ISSUE TITLE
GeoLiteCity databases updating

### ISSUE THREAD

**Issue by TheThingGoesSkra** [securestate/king-phisher#418]
To warn you, the databases used during the installation process are no longer available.

This link is deprecated: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz  

Like explained in this section: 
https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by zeroSteiner** [comment]
Looks like the update logic will have to be removed. Folks will have to use the script that MaxMind provides after registering for an account to get the database.

**Comment by smcintyre-r7** [comment]
Looking into the long term solution for this and based on [this](https://support.maxmind.com/geolite-faq/general/how-do-i-use-the-geolite2-databases-in-a-product-or-service/) page it looks like the only option is to require users to get the database for themselves. Options 1 and 2 which would allow me to directly redistribute it won't work because I can't "flow down" the applicable requirements based on KP being open source and users not registering with me.

I'll remove the options to update the database that isn't working and then I'll have to update the install documentation to add a step that must be manually taken to register with a 3rd party site (maxmind) which is less than ideal.

**Comment by zeroSteiner** [comment]
Looking into the long term solution for this and based on [this page](https://support.maxmind.com/geolite-faq/general/how-do-i-use-the-geolite2-databases-in-a-product-or-service/) it looks like the only option is to require users to get the database for themselves. Options 1 and 2 which would allow me to directly redistribute it won't work because I can't "flow down" the applicable requirements based on KP being open source and users not registering with me.

I'll remove the options to update the database that isn't working and then I'll have to update the install documentation to add a step that must be manually taken to register with a 3rd party site (maxmind) which is less than ideal.

**Comment by zeroSteiner** [comment]
Alright this has been fixed in commit 51185b4a2afd7e70bc8436c50550258cf0465f6e. The solution is in two parts, 
1) I've removed the automatic GeoIP update code since it won't work without a license key any more.
2) I've started to distribute a GeoIP database directly to avoid requiring users to register with a third party site before the server will start. The distributed database is from 2019-12-24 and is the last database MaxMind released prior to their changes. I will not be able to update this database, if users want a newer copy they'll need to register their own account and download their own copy.

Thanks for bringing this to my attention, I'm going to close out this issue as it has been resolved to the best of my ability.
