### ISSUE TITLE
RHEL 7 Supported?

### ISSUE THREAD

**Issue by snider14** [securestate/king-phisher#56]
Hello Spencer,

I was wondering if RHEL 7 is supported yet by King Phisher? Last that I asked about this I was told that it does not yet support Red Hat. Thanks!

**Comment by zeroSteiner** [comment]
Unfortunately I can't say it does because I don't have access to a RHEL
system for testing. You could try running the install script and setting
LINUX_VERSION on line 33 to either CentOS or Fedora, which would be the two
closest supported flavors. The install script just sets up and installs all
of the packages, so if you can get all of the dependencies installed so
"pip install -r requirements.txt" runs successfully everything should be
good to go. Additionally if you're trying to install the server on RHEL you
can simplify the installation process by specifying to skip the client
packages (which has more) by running the install script like
"KING_PHISHER_SKIP_CLIENT=TRUE
./install.sh".

I hope that helps,
Spencer

**Comment by snider14** [comment]
Thanks for the info! We will give it a shot.

**Comment by zeroSteiner** [comment]
I'm going to close this out as the question has been answered. If you wouldn't mind I'd appreciate an update either way on whether you're successful or not in installing on RHEL 7.
