### ISSUE TITLE
Support of gir-vte 2.91

### ISSUE THREAD

**Issue by sbrun** [securestate/king-phisher#61]
debian/testing and upcoming kali release both provide gir1.2-vte-2.91 and no longer gir1.2-vte-2.90. I don't know if there are relevant API changes between both versions but you should consider using 2.91 by default and ensuring that it works with this version.
We just uploaded a package for kali-rolling with a manual change to the gi.require_version call and it seems to start at least...

**Comment by zeroSteiner** [comment]
Support for VTE-2.91 is already in, the only API difference for what king phisher needs is [here](https://github.com/securestate/king-phisher/blob/master/king_phisher/client/windows/rpc_terminal.py#L148-L157). Because both 2.90 and 2.91 are supported, the `gi.require_version` is left out. I'm not aware of a good way to call `gi.require_version` without error handling when multiple versions are supported as is the case with VTE and WebKit2.

Thanks for the heads up on this though. Was the client not starting at all on Kali without a call to `gi.require_version`? If it wasn't starting could I get the output of a stack trace with debugging turned on (`-L DEBUG`)?

**Comment by sbrun** [comment]
It's great that's support for VTE-2.91 is in.
If I dropped the call to |gi.require_version|, the client started but
there was a warning (same thing with WebKit2). I decided to patch the
code to require the correct version.

**Comment by zeroSteiner** [comment]
Ok that makes sense then. Due to the warning not being fatal this isn't a bug, so I'm going to close it out. Finding a better way to use `gi.require_version` when two or more versions are supported is on my long to do list but I'll try to get it done for the next release to remove the warning. Thanks!

**Comment by zeroSteiner** [comment]
I looked into this some more and found a way to enumerate the available versions for gi namespaces. Commit 88b65da97dab46d4145f38d475f640211b69460c includes this logic to select the latest supported versions of WebKit2 and Vte. The warning message should no longer be appearing.
