### ISSUE TITLE
Help:Not able to install King-phisher in Kali 2016.1

### ISSUE THREAD

**Issue by anurag2994** [securestate/king-phisher#65]
I see this when I try to run install.sh
![screenshot from 2016-02-05 01-14-57](https://cloud.githubusercontent.com/assets/13747230/12827478/f2c224be-cba5-11e5-9d6e-c6389552ba3d.png)

**Comment by zeroSteiner** [comment]
So, if you have Kali 2016.1 you will be glad to know that King Phisher is provided by the package manager. It should have been installed by default however if it wasn't you can try reinstalling it with `apt-get install king-phisher`. Once King Phisher is installed on Kali it's available in the `/usr/share/king-phisher` directory.

Because users should also be able to install it from source like you are trying, I'll update the install script to properly detect the rolling version of Kali.

**Comment by anuraguk200** [comment]
Yes it was pre-installed but that wasn't working. I was not able to run the king-phisher server. When I tried to run it on another Kali version by downloading it from git, it was working fine. So I tried to install it through git.

**Comment by anuraguk200** [comment]
I always get this error. There is some error in the configuration of the king-phisher server.
Please help! Thanks a lot!
![screenshot from 2016-02-05 01-51-19](https://cloud.githubusercontent.com/assets/13747230/12828474/1411d8f8-cbab-11e5-9dbe-b9e7e673b4ec.png)

**Comment by zeroSteiner** [comment]
So you're trying to connect to a local server instance. Is the server running and listening on port 80? Should start out by checking that with netstat.

**Comment by anuraguk200** [comment]
There's no netstat in Kali. 'ss' is an alternative to that. I checked its not listening on port 80.
![rsz_screenshot_from_2016-02-05_12-50-26](https://cloud.githubusercontent.com/assets/13747230/12840214/642faea8-cc07-11e5-9a09-e9d8806652be.png)

**Comment by zeroSteiner** [comment]
Well that would be why the client can't connect. The server needs to be started first. Once the server is running you can try connecting with the client again.

**Comment by wolfthefallen** [comment]
anuraguk200 to correct the issue with king-phisher in 2016.1 Kali Linux Rolling version:
```BASH
pip install "py2-ipaddress==3.4.1"
pip install --force-reinstall -I pytz
```

**Comment by wolfthefallen** [comment]
following up to see if you where able to get king-phisher to work successfully with the fix above.

**Comment by anurag2994** [comment]
Sorry, i couldn't had been a little busy. Didn't check. And no it's still not working man!

**Comment by wolfthefallen** [comment]
Its ok I know how we get busy with things. You should be able to use the prepacked king-phisher install after completing the pip installs. Commented above. You will need to start a couple of services then you should be good to go.

```BASH
systemctl start king-phisher
systemctl start ssh
```
start the king-phisher client.
```BASH
cd /usr/share/king-phisher/
./KingPhisher
```
provide the information for the client. IE.
Server: localhost
username: root
password: toor
click login.

if you want to install King-Phisher from git. The PR((https://github.com/securestate/king-phisher/pull/66) for kali rolling support landed last night. Please merge your git repository with master to receive the update. We recommend only using King-Phisher from git repository if you are planning on conducting development work or testing the dev branch. As with all Kali packages, installing from source could break dependencies for other tools in the distro.

**Comment by anurag2994** [comment]
I'll try this later. i removed the pre-installed one. I just downloaded the file from here. I think you have updated the setup file and now I'm not getting the that error "kali wasn;t found".  It's getting installed. If still it doesn't work I'll the thing you suggested above.

**Comment by anurag2994** [comment]
After executing "systemctl start king-phisher"

It says "Failed to start king-phisher.service: Unit king-phisher.service is masked."

**Comment by wolfthefallen** [comment]
systemctl unmask king-phisher.service

**Comment by anurag2994** [comment]
i don't think it is ever gonna work on my computer! I'm getting this now "Job for king-phisher.service failed because a configured resource limit was exceeded. See "systemctl status king-phisher.service" and "journalctl -xe" for details."

**Comment by anurag2994** [comment]
After executing "systemctl status start king-phisher"
● start.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; disabled; vendor preset: enabled)
   Active: failed (Result: resources) since Sun 2016-02-07 21:53:48 IST; 2min 34s ago
  Process: 12222 ExecStart=/opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=0/SUCCESS)

Feb 07 21:53:48 mr-robot KingPhisherServer[12222]: File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
Feb 07 21:53:48 mr-robot KingPhisherServer[12222]: return self.dbapi.connect(*cargs, **cparams)
Feb 07 21:53:48 mr-robot KingPhisherServer[12222]: File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
Feb 07 21:53:48 mr-robot KingPhisherServer[12222]: conn = _connect(dsn, connection_factory=connection_factory, async=async)
Feb 07 21:53:48 mr-robot KingPhisherServer[12222]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authenticat...hisher"
Feb 07 21:53:48 mr-robot KingPhisherServer[12222]: FATAL:  password authentication failed for user "king_phisher"
Feb 07 21:53:48 mr-robot systemd[1]: king-phisher.service: Daemon never wrote its PID file. Failing.
Feb 07 21:53:48 mr-robot systemd[1]: Failed to start King Phisher Server.
Feb 07 21:53:48 mr-robot systemd[1]: king-phisher.service: Unit entered failed state.
Feb 07 21:53:48 mr-robot systemd[1]: king-phisher.service: Failed with result 'resources'.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by wolfthefallen** [comment]
please verify that the username and password for your database <url> in your /opt/king-phisher/server_config.yml is correct. [yml sever example](https://github.com/securestate/king-phisher/blob/master/data/server/king_phisher/server_config.yml#L39). Please note you can do PostgreSQL database which is preferred. The data PostgreSQL url format is postgresql://<username>:<password>@<server>/<database> IE postgresql://king-phisher:reallylongpassword@localhost/king-phisher. IF the password is incorrect and you are using a PostgreSQL database. change the password by doing the following starting as the **root** user.
```BASH
su postgres
psql
\password king-phisher (or the username for the database in your url)
\q
```

**Comment by anurag2994** [comment]
Hello I'm really sorry, it has been a long week, didn't get time at all. Man it's still not working I changed the password too.

**Comment by anurag2994** [comment]
I have set my database to postgresql. I changed its password and changed the password in the yml file too. It's not working.

**Comment by wolfthefallen** [comment]
That's understandable. Are you still getting the same stack trace dump when trying to start the server?

**Comment by Str0m** [comment]
try this 

`cd /usr/share/king-phisher/`

`./KingPisherServer -L INFO -f system server_config.yml`

it shuld throw a error !

do this 
`su postgres`
`psql`
`ALTER USER king_phisher WITH PASSWORD 'your password';`

 make sure that database(postgres) password  is the same in the system server_config.yml

then 
you have to change the port where king phiser server is listening

edit the  `server_config.yml`

`server:
  # Bind address information
  address:
    host: 0.0.0.0
    port: 8080

`
start again 
`./KingPisherServer -L INFO -f system server_config.yml`

you shuld se something like this

`INFO     listening on 0.0.0.0:8080
INFO     0.0.0.0:8080 - serving files has been enabled
INFO     initializing database connection with driver postgresql
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
INFO     the job manager has been started
WARNING  the specified geoip database does not exist, downloading a new copy
INFO     Starting new HTTP connection (1): geolite.maxmind.com
INFO     server running in process: 17712 main tid: 0x7f6febcf8700
INFO     dropped privileges to the nobody account
`

start the client 
 `./KingPhisher`

and change the port  80 to 8080

Sorry for my english !

**Comment by anurag2994** [comment]
I fixed the postgresql authetication problem. But now I'm getting this error:

Feb 20 13:08:29 mr-robot systemd[1]: Starting King Phisher Server...
Feb 20 13:08:29 mr-robot systemd[1]: king-phisher.service: PID file /var/run/king-phisher.pid not readable (yet?) after start: No such file or directory
Feb 20 13:08:32 mr-robot KingPhisherServer[5169]: WARNING  the specified geoip database does not exist, downloading a new copy
Feb 20 13:09:59 mr-robot systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Feb 20 13:09:59 mr-robot systemd[1]: Failed to start King Phisher Server.
Feb 20 13:09:59 mr-robot systemd[1]: king-phisher.service: Unit entered failed state.
Feb 20 13:09:59 mr-robot systemd[1]: king-phisher.service: Failed with result 'timeout'.

**Comment by wolfthefallen** [comment]
Can you please start the King Phisher server in debug mode and provide the stack trace when it fails out. 

```BASH
sudo ./KingPhisherServer -L DEBUG server_config.yml
```

Or you can change your server_config.yml logging level, and provide the information from your king_phisher.log file when you try to start it with systemd.

[server logging level](https://github.com/securestate/king-phisher/blob/4c19df7bd25bf6450002b09a26515119e37be8b2/data/server/king_phisher/server_config.yml#L7)

With the current logging you provided it appears that the it is not being able to download the geoip database. Please make sure your system can access.

[http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz](url)

With the server in DEBUG mode we will be able to confirm  if that is the issue.

**Comment by anurag2994** [comment]
Hi thanks a lot! It's working now! Finally!!!!!!!!!!

![screenshot from 2016-02-20 19-55-24](https://cloud.githubusercontent.com/assets/13747230/13197185/1aa7bae4-d80c-11e5-96c2-8168f39020e9.png)

**Comment by wolfthefallen** [comment]
Awesome!

I'm going to close out the issue, if you have any other problems let us know.

**Comment by anurag2994** [comment]
hey there is something that I think you can help me with. Are you on twitter?

**Comment by wolfthefallen** [comment]
I do have a twitter account @Wolf_TheFallen

**Comment by d4rk140r** [comment]
I cant connet to server....this is what i got
![help](https://cloud.githubusercontent.com/assets/17787065/14268331/554b1fe6-fa9f-11e5-9125-ba58d10bed54.png)

**Comment by zeroSteiner** [comment]
@d4rk140r please open a new issue for support requests. It helps keep issues organized and on topic. It looks like you're having connectivity issues. You should double check that the server is running and that it is correctly specified in the client.

**Comment by r00t-ph03n1x** [comment]
Here is the complete tutorial of installing king-phisher:

At first, 
uninstall king-phisher by using this command:
apt-get remove king-phisher along with all files from usr/share/ and etc/
=================================================================================================
then clone this repo to /op/ directory.
the install king-phisher by using install.sh from tools directory.
install postgresql during installation
also install latest requirements using pip install -r requirements.txt from king-phisher directory
=================================================================================================
after the installation,
First find the pg_hba.conf file and add the following line:

host     king_phisher    king_phisher   127.0.0.1/32            md5
=================================================================================================
then,
execute the following command: 
su postgres 
dropdb king_phisher
again type this command:       
dropuser king_phisher
after deleting the postgresql user for king phisher, type this command:
createuser king_phisher -P
Enter your new password: toor
Enter it again: toor
createdb --owner=king_phisher king_phisher
Exit
=================================================================================================
then edit the configaration file named server_config.yml
postgresql://username:password@localhost/database_name 
with the new settings
postgresql://king_phisher:toor@localhost/king_phisher
and 
change the bind server information like this:

# Bind address information, multiple ports can be
addresses:
- host: 0.0.0.0
port: 8080
ssl: false
================================================================================================
execute the following command: 
pip install "py2-ipaddress==3.4.1" --upgrade
pip install --force-reinstall -I pytz
in the king-phisher directory
================================================================================================
Then execute the command in /opt/king-phisher directory:
./KingPhisherServer -L INFO -f server_config.yml

output:

WARNING  python 2.7 support is deprecated, see https://github.com/securestate/king-phisher/wiki/Python-3 for details
INFO     listening on 0.0.0.0:8080
INFO     serving files has been enabled
INFO     initializing database connection with driver sqlite
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
INFO     the job manager has been started
WARNING  the specified geoip database does not exist, downloading a new copy
INFO     server running in process: 2193 main tid: 0x7f17c7fdd700
INFO     dropped privileges to the nobody account
WARNING  sqlite is no longer fully supported, see https://github.com/securestate/king-phisher/wiki/Database#sqlite for more details
================================================================================================
start the client
./KingPhisher 

The output will be:
ARNING  it is not necessary to run the king phisher client as root
WARNING  python 2.7 support is deprecated, see https://github.com/securestate/king-phisher/wiki/Python-3 for details
ERROR    css parser error (not a number) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:98
ERROR    css parser error (Expected a string.) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:98
ERROR    there was an error parsing the css file, it will not be applied as a style provider
================================================================================================
The full settings of server_config.yml in kali linux 2016.2:

#
# King-Phisher Server Configuration
#

logging:
  file: /var/log/king-phisher.log
  # Available levels: FATAL, ERROR, WARNING, INFO, DEBUG
  level: warning
  console: false

server:
  # Bind address information, multiple ports can be
  addresses:
    - host: 0.0.0.0
      port: 8080
      ssl: false

  # Server RPC authentication related settings
  #authentication:
    # How long to cache authentication information in the server process
    #cache_timeout: 10m
    # Require authenticating users to be a member of the specified group
    #group: king-phisher
    # The service to use for PAM authentication
    #pam_service: sshd
    # How long an authenticated RPC session should be valid for after no
    # requests have been received.
    #session_timeout: 30m

  # A cookie to retrieve the client's IP from, useful when a proxy is in place
  #client_ip_cookie: X-Real-IP

  # The name of the cookie used to track users
  cookie_name: KPID

  # Specify an additional search path for server data files
  data_path: /opt/king-phisher

  # The SQLite3 database file to use, the folder needs write permissions
  # WARNING: SQLite3 is not fully supported as of version 0.1.6, see
  # https://github.com/securestate/king-phisher/wiki/Database#sqlite for more
  # details
  database: sqlite:////var/king-phisher/king-phisher.db

  # The PostgreSQL database to use
  #database: postgresql://king_phisher:toor@localhost/king_phisher

  # Fork the server process into the background
  fork: true

  geoip:
    # The location of the GeoLite2 City database
    database: /var/king-phisher/geoip.mmdb

  # Set a file to write the PID to
  pid_file: /var/run/king-phisher.pid

  # Add additional search paths for plugin directories
  #plugin_directories:
  #  - /some/plugin/path
  # List the plugins that need to be enabled
  #plugins:
  #  # The plugin to enable's name
  #  some_plugin:
  #    # An option specific to this particular plugin
  #    value_for_some_plugin: true

  # Require an ID associated with a campaign to load pages
  require_id: true

  rest_api:
    enabled: false
    # Networks which are authorized to use the REST API
    networks:
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    # When null the token will be randomized at run time
    token: null

  # Configure the server header value
  #server_header: Apache/2.4.9 (Unix)

  # Set the opened timestamp on the first visit if it's null
  set_message_opened_on_visit: true

  # Drop privileges to the specified user
  setuid_username: nobody

  # Default SSL certificate settings
  #ssl_cert: /path/to/ssl.crt
  #ssl_key: /path/to/ssl.key
  # Hostname specific SSL certificates can be added below
  #ssl_hosts:
  #  - host: www.king-phisher.com
  #    ssl_cert: /path/to/www.king-phisher.com/ssl.crt
  #    ssl_key: /path/to/www.king-phisher.com/ssl.key

  # Configure the image file name used to track opened emails
  tracking_image: email_logo_banner.gif

  # Use subfolders in the web_root which correspond to vhost names
  vhost_directories: false
  web_root: /var/www
=================================================================================================
The full settings of pg_hba.conf of postgresql both 9.6 and 9.5 in kali linux 2016.2:

# PostgreSQL Client Authentication Configuration File
# ===================================================
#
# Refer to the "Client Authentication" section in the PostgreSQL
# documentation for a complete description of this file.  A short
# synopsis follows.
#
# This file controls: which hosts are allowed to connect, how clients
# are authenticated, which PostgreSQL user names they can use, which
# databases they can access.  Records take one of these forms:
#
# local      DATABASE  USER  METHOD  [OPTIONS]
# host       DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostssl    DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostnossl  DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
#
# (The uppercase items must be replaced by actual values.)
#
# The first field is the connection type: "local" is a Unix-domain
# socket, "host" is either a plain or SSL-encrypted TCP/IP socket,
# "hostssl" is an SSL-encrypted TCP/IP socket, and "hostnossl" is a
# plain TCP/IP socket.
#
# DATABASE can be "all", "sameuser", "samerole", "replication", a
# database name, or a comma-separated list thereof. The "all"
# keyword does not match "replication". Access to replication
# must be enabled in a separate record (see example below).
#
# USER can be "all", a user name, a group name prefixed with "+", or a
# comma-separated list thereof.  In both the DATABASE and USER fields
# you can also write a file name prefixed with "@" to include names
# from a separate file.
#
# ADDRESS specifies the set of hosts the record matches.  It can be a
# host name, or it is made up of an IP address and a CIDR mask that is
# an integer (between 0 and 32 (IPv4) or 128 (IPv6) inclusive) that
# specifies the number of significant bits in the mask.  A host name
# that starts with a dot (.) matches a suffix of the actual host name.
# Alternatively, you can write an IP address and netmask in separate
# columns to specify the set of hosts.  Instead of a CIDR-address, you
# can write "samehost" to match any of the server's own IP addresses,
# or "samenet" to match any address in any subnet that the server is
# directly connected to.
#
# METHOD can be "trust", "reject", "md5", "password", "gss", "sspi",
# "ident", "peer", "pam", "ldap", "radius" or "cert".  Note that
# "password" sends passwords in clear text; "md5" is preferred since
# it sends encrypted passwords.
#
# OPTIONS are a set of options for the authentication in the format
# NAME=VALUE.  The available options depend on the different
# authentication methods -- refer to the "Client Authentication"
# section in the documentation for a list of which options are
# available for which authentication methods.
#
# Database and user names containing spaces, commas, quotes and other
# special characters must be quoted.  Quoting one of the keywords
# "all", "sameuser", "samerole" or "replication" makes the name lose
# its special character, and just match a database or username with
# that name.
#
# This file is read on server startup and when the postmaster receives
# a SIGHUP signal.  If you edit the file on a running system, you have
# to SIGHUP the postmaster for the changes to take effect.  You can
# use "pg_ctl reload" to do that.

# Put your actual configuration here
# ----------------------------------
#
# If you want to allow non-local connections, you need to add more
# "host" records.  In that case you will also need to make PostgreSQL
# listen on a non-local interface via the listen_addresses
# configuration parameter, or via the -i or -h command line switches.




# DO NOT DISABLE!
# If you change this first entry you will need to make sure that the
# database superuser can access the database using some other method.
# Noninteractive access to all databases is required during automatic
# maintenance (custom daily cronjobs, replication, and similar tasks).
#
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5
host     king_phisher    king_phisher    127.0.0.1/32            md5
===================================================================================================

Enjoy =D

**Comment by shad0wman** [comment]
sir,

Your last email is incredibly hard to read because of the bold, extra large fonts. Could you please fix your fonts so they are readable and resend your last so I can better understand what's going on?


Thanks


________________________________

**Comment by zeroSteiner** [comment]
Additionally @r00t-ph03n1x, this issue has been closed. If you're experiencing issues please open a new ticket so we can track it separately.
