### ISSUE TITLE
Unable to send email via smtp using kingphisher

### ISSUE THREAD

**Issue by itmaniac** [securestate/king-phisher#91]
## Issue Description
my kingphisher & postfix application is successfully installed on ubutnu 15.10. now after configuring the kingphisher to send email, the sending logs show that it connects to smtp server, sends email successfully and then disconnected but when i open my email accounts on gmail and hotmail, there is no email received. even the junk folder are empty.
Kindly help me to understand how to send email from my linux machine to external email account with the kingphisher email.

## Reproduction Steps
postfix main.cf file is attached for your review.

## Error Details / Stack Trace
kindly review the attached snapshot for sending email logs messages
[King Phisher.zip](https://github.com/securestate/king-phisher/files/198477/King.Phisher.zip)

**Comment by zeroSteiner** [comment]
We don't provide postfix support, that is outside of the scope of the project. Once King Phisher has sent the email to the SMTP server successfully it is outside of our control and up to the SMTP server to ensure it's delivery and even in that case the SMTP server may deliver it to another only for it to end up in the junk folder.

Having said that, I would start out with some basic trouble shooting. I noticed that you're trying to send messages to GMail. Google's spam filters are pretty advanced and check for things such as SPF. If the SPF record fails because you're spoofing from a domain you don't own, then the message will likely not be delivered. Check the postfix logs and see if the message was successfully delivered or not. Also try sending the same message to another email server that you are authorized to use for testing to ensure and debug it's delivery.

Barring all else you can seek support from Postfix, but from King Phisher's perspective it's delivered the message to the SMTP server and it's up to the server and the user configuring King Phisher to ensure that it is delivered.
