### ISSUE TITLE
Unable to create Clone page

### ISSUE THREAD

**Issue by itmaniac** [securestate/king-phisher#92]
## Issue Description
We successfully solved the smtp issue. thank your for your help. now we are sending test email but when we try to clone any webpage via clone page feature, it is giving error.
[cloner issue.zip](https://github.com/securestate/king-phisher/files/200229/cloner.issue.zip)

Kindly help us to resolve this issue.

Also guide us, once this clone is done, shall we replace this clone webpage with on-line/live website index.html file?

## Reproduction Steps
1. KingPhisher -> Tools -> Clone webpage

## Error Details / Stack Trace
snapshot is attached for error review.

**Comment by zeroSteiner** [comment]
Thanks, I'm going to take a look at this. In the future, it would be very helpful if you could copy the contents of the error details in the dialog and paste them into the issue. That will help us keep track of the details without having to dig through the ZIP and read the details from the image.

**Comment by zeroSteiner** [comment]
As it turns out WebKit2.URIResponse.get_http_headers is available [since v2.6](http://webkitgtk.org/reference/webkit2gtk/stable/WebKitURIResponse.html#webkit-uri-response-get-http-headers). I'm pretty confident that the issue here is that Ubuntu 15.10 has an older version of WebKit2. This issue has been addressed in commit 455e555 and has been pushed up to the dev branch.

Thanks for reporting this issue!
